import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import LogoutBtn from "./LogoutBtn";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth" 
import Signup from "./Signup";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({ children }) {

  let session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        
        <div className="navbar" >
          
          <Link href='/about' style={{fontWeight:"bold"}}>SSblog</Link>
          
          <Link href='/about'>소개</Link>
        
          <Link href='/routine'>글 포스팅</Link>
          <Link href='/post'>커뮤니티</Link>

          {
            session ? <LogoutBtn/> : <LoginBtn/>
          }
          {
            session ? null : <Signup/>
          }
        </div>
      
        <div className="main-container">
        <div className="main-banner maximum-width">
          <h1>제 하루 일상루틴을 공유하는 블로그입니다.</h1>
          <p style={{color:"brown"}}>"Rome wasn't built in a day"</p>
        </div>

      
   </div>

        {children}
        </body>
    </html>
  );
}
